### ISSUE TITLE
Please include in ELPA

### ISSUE THREAD

**Issue by gnusupport** [stardiviner/kiwix.el#3]
Please include the package in ELPA to make it available to many users.

**Comment by stardiviner** [comment]
Don't know how to include package in ELPA, do you want to submit to ELPA? That's will be great.

**Comment by gnusupport** [comment]
To submit package to GNU ELPA you would need to provide copyright
assignment to Free Software Foundation as they are helping in
protection of a package, you retain full control and continue
programming and improving it.

* stardiviner <notifications@github.com> [2020-12-17 02:51]:
> Don't know how to include package in ELPA, do you want to submit to
> ELPA? That's will be great.

I cannot submit as I am not author, but you can. You may write to
emacs-devel@gnu.org and say that you need help how to do it and
provide link to the package.

We discussed it as we consider including maybe that package in new
nonGNU ELPA repository, but it lacks clear licensing and header.

Jean

**Comment by stardiviner** [comment]
I sent email to emacs-devel mailing list already. After communication, I think this package still have some problems. So seems not ready to be in ELPA yet.

**Comment by gnusupport** [comment]
* stardiviner <notifications@github.com> [2020-12-19 10:11]:
> I sent email to emacs-devel mailing list already. After
> communication, I think this package still have some problems. So
> seems not ready to be in ELPA yet.

Yes, but you continue and improve package.

**Comment by stardiviner** [comment]
This package requires `request` currently not in ELPA yet, and after a search and some work, still don't know how to submit to ELPA. Mind crashed..... Give up.

**Comment by gnusupport** [comment]
* stardiviner <notifications@github.com> [2020-12-19 12:20]:
> This package requires `request` currently not in ELPA yet, and after
> a search and some work, still don't know how to submit to ELPA. Mind
> crashed..... Give up.

What does `request' do? Does it fetch URL?

**Comment by stardiviner** [comment]
It's an wrapper on `url.el`.

**Comment by gnusupport** [comment]
* stardiviner <notifications@github.com> [2020-12-19 13:28]:
> It's an wrapper on `url.el`.

For time being you could use url.el so that your package enters GNU
ELPA and once it gets improved you may use some other function later.

Is that possible? Does it fetch much?

**Comment by stardiviner** [comment]
No, request.el is a requirement for me. Can't switch to use `url.el`. Also seems one maintainer already decide to include `request.el`. Currently contactting author, but have not got reply from author.

**Comment by gnusupport** [comment]
* stardiviner <notifications@github.com> [2020-12-22 12:12]:
> No, request.el is a requirement for me. Can't switch to use
> `url.el`. Also seems one maintainer already decide to include
> `request.el`. Currently contactting author, but have not got reply
> from author.

I hope for solution to come. 

I do not even know why you use fetching, is it one time or something
that package always does?

**Comment by stardiviner** [comment]
After a long conversation with Stefan Monnier who maintain Emacs ELPA. kiwix.el is included in ELPA now. Should be available soon.

**Comment by gnusupport** [comment]
* stardiviner <notifications@github.com> [2020-12-29 18:42]:
> After a long conversation with Stefan Monnier who maintain Emacs
> ELPA. kiwix.el is included in ELPA now. Should be available soon.

That is great!
