### ISSUE TITLE
Is the software GPL version 3.0 or GPL version 3.0 and later?

### ISSUE THREAD

**Issue by gnusupport** [stardiviner/kiwix.el#4]
Please clarify this question

**Comment by gnusupport** [comment]
Could you please see the convention on packaging in Emacs Lisp manual and include the license information in the package itself. As package is distributed without license information and then users get proprietary package and do not know how to distribute it. I have tried looking for licensing information but did not find it. I found the LICENSE file, but that is not enough yet.

**Comment by stardiviner** [comment]
Included license info in source code file now.

**Comment by gnusupport** [comment]
* stardiviner <notifications@github.com> [2020-12-17 03:24]:
> Included license info in source code file now.

That is great.

Richard Stallman uses Kiwix and asked why this package miss the
license.

Could you please write to emacs-devel@gnu.org and say that you wish to
include kiwix.el into GNU ELPA?

Thank you

**Comment by stardiviner** [comment]
Sure, I will do it soon. Thanks @gnusupport
