### ISSUE TITLE
selectrum-read has been made private

### ISSUE THREAD

**Issue by minad** [stardiviner/kiwix.el#5]
I found your project while searching for `selectrum-read` API usage. The API has been deprecated, see https://github.com/raxod502/selectrum/pull/446 and https://github.com/raxod502/selectrum/pull/443. You can still continue to use `selectrum--read` as an alternative. However this is discouraged and could lead to breakage later on. I would rather encourage you to look into my [Consult](https://github.com/minad/consult) package, which supports a completion-system agnostic async API (which is also private as of now, since the package is still young). You can send a search query and the candidate list is asynchronously populated. See for example the command `consult-ripgrep` or the [consult-spotify](https://codeberg.org/jao/espotify/src/branch/main/consult-spotify.el) package which also queries a web api.

**Comment by stardiviner** [comment]
Ok, I will update recently. Thanks for contacting. @minad

**Comment by stardiviner** [comment]
@minad The consult API is too complex to understand. Is there simple API for invoke like `selectrum-read`?

**Comment by minad** [comment]
No, there is no simpler API. The advantage is that you get asynchronous instead of synchronous queries in contrast to now.

**Comment by stardiviner** [comment]
The original `selectrum-read` is not async queries? I see. Really complex to write.

**Comment by minad** [comment]
> The original selectrum-read is not async queries? I see. Really complex to write.

No, it is not. The lambda passed to selectrum-read receives the input string and returns the result. You also have: https://github.com/stardiviner/kiwix.el/blob/0c5e1619f079df822686cf42af5859111b6afd44/kiwix.el#L243 If you want to find out how to use the API I suggest you check out the [consult-spotify](https://codeberg.org/jao/espotify/src/branch/main/consult-spotify.el) package. It is a literate library with extensive comments.

**Comment by stardiviner** [comment]
I checked. Lucky that I don't need to do much work to change the api. I will record it down load my Org note.
